language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src/

before_install:
- export TZ=Asia/Jakarta

install:
- pip install -U platformio
- platformio update 
- platformio lib install 567
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%y%m%d%H%M%S')}

script:
- platformio run -e nodemcuv2
- platformio --version

deploy:
  skip_cleanup: true
  overwrite: true
  provider: releases
  api_key: $TOKEN
  file: ".pio/build/nodemcuv2/firmware.bin"
  on:
    repo: SyadzwinaLD/buff
    all_branches: true


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# install:
#     - pip install -U platformio
#     - platformio update
#
# script:
#     - platformio run


#
# Template #2: The project is intended to be used as a library with examples.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# env:
#     - PLATFORMIO_CI_SRC=path/to/test/file.c
#     - PLATFORMIO_CI_SRC=examples/file.ino
#     - PLATFORMIO_CI_SRC=path/to/test/directory
#
# install:
#     - pip install -U platformio
#     - platformio update
#
# script:
#     - platformio ci --lib="." --board=ID_1 --board=ID_2 --board=ID_N
